services:
  mongodb-booking:
    image: mongo:latest
    container_name: mongodb-booking
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-booking
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb-booking

volumes:
  mongo_data:
